// 子モジュールに、各疑似乱数のテストを記述する
// 連続型確率変数
mod test_uniform; // 一様分布
mod test_normal; // 正規分布
mod test_half_normal; // 半正規分布
//mod test_log_normal; // 対数正規分布
mod test_cauchy; // コーシー分布
mod test_half_cauchy; // 半コーシー分布
mod test_levy; // レヴィ分布
mod test_exponential; // 指数分布
mod test_laplace; // ラプラス分布
mod test_rayleigh; // レイリー分布
//mod test_weibull; // ワイブル分布
//mod test_gunbel; // ガンベル分布
//mod test_gamma; // ガンマ分布
//mod test_beta; // ベータ分布
//mod test_dirichlet; // ディリクレ分布
//mod test_power_function; // べき関数分布
//mod test_exponential_power; // 指数べき分布
//mod test_erlang; // アーラン分布
//mod test_chi_square; // ガンマ二乗分布
//mod test_chi; // ガンマ分布
//mod test_f; // F分布
//mod test_t; // t分布
//mod test_inverse_gaussian; // 逆ガウス分布
//mod test_triangular; // 三角分布
//mod test_pareto; // パレート分布
//mod test_logistic; // ロジスティック分布
//mod test_heyperbolic_secant; // 双曲線正割分布
//mod test_raised_cosine; // 余弦分布
//mod test_arcsine; // 逆正弦分布
//mod test_von_mises; // フォン・ミーゼス分布
//mod test_non_central_gamma; // 非心ガンマ分布
//mod test_non_central_beta; // 非心ベータ分布
//mod test_non_central_chi_square; // 非心ガンマ二乗分布
//mod test_non_central_chi; // 非心ガンマ分布
//mod test_non_central_f; // 非心F分布
//mod test_non_central_t; // 非心t分布
//mod test_plank; // プランク分布

// 離散型確率変数
mod test_bernoulli; // ベルヌーイ分布
//mod Binomial // 二項分布
mod test_geometric; // 幾何分布
//mod test_Poisson // ポアソン分布
//mod test_HeyperGeometric // 超幾何分布
//mod test_Multinominal // 多項分布
//mod test_NegativeBinomial // 負の二項分布
//mod test_NegativeHeyperGeometric // 負の超幾何分布
//mod test_LogarithmicSeries // 対数級数分布
//mod test_YuleSimon // ユール・シモン分布
//mod test_ZipfMandelbrot // ジップ・マンデルブロート分布
//mod test_Zeta // ゼータ分布